// ------------------ EVENT ORGANIZER LOGIC ------------------

// Add New Event
function addEvent() {
  const name = document.getElementById('eventName')?.value.trim();
  const location = document.getElementById('eventLocation')?.value.trim();
  if (!name || !location) return alert('Please enter both name and location.');

  const eventText = `${name} @ ${location}`;

  const li = document.createElement('li');
  li.innerText = eventText;
  document.getElementById('eventList').appendChild(li);

  let events = JSON.parse(localStorage.getItem('eventList') || '[]');
  events.push(eventText);
  localStorage.setItem('eventList', JSON.stringify(events));

  showToast(`✅ "${eventText}" added!`);

  document.getElementById('eventName').value = '';
  document.getElementById('eventLocation').value = '';
}

// Load saved events
function loadEvents() {
  const ul = document.getElementById('eventList');
  if (!ul) return;
  let events = JSON.parse(localStorage.getItem('eventList') || '[]');
  events.forEach(event => {
    const li = document.createElement('li');
    li.innerText = event;
    ul.appendChild(li);
  });
}

// Communication Panel Send
function setupCommunicationPanel() {
  const sendBtn = document.querySelector('.glow-button.send-message');
  const messageBox = document.querySelector('textarea[placeholder*="Type message"]');
  if (sendBtn && messageBox) {
    sendBtn.addEventListener('click', () => {
      const msg = messageBox.value.trim();
      if (!msg) return alert("⚠️ Type a message first.");
      showToast(`📨 Sent: "${msg}"`);
      messageBox.value = '';
    });
  }
}

// Upload Missing Person
function setupMissingUpload() {
  const uploadBtn = document.querySelector('.glow-button.upload-missing');
  const fileInput = document.querySelector('input[type="file"]');
  if (uploadBtn && fileInput) {
    uploadBtn.addEventListener('click', () => {
      if (!fileInput.files.length) return alert("⚠️ Upload a photo first.");
      const reader = new FileReader();
      reader.onload = () => {
        localStorage.setItem('missingPersonImage', reader.result);
        alert("📸 Face uploaded. Drone is scanning...");
      };
      reader.readAsDataURL(fileInput.files[0]);
    });
  }
}

// Report Generator
function setupReportGenerator() {
  const reportBtn = document.querySelector('.glow-button.generate-report');
  if (reportBtn) {
    reportBtn.addEventListener('click', () => {
      const eventList = JSON.parse(localStorage.getItem('eventList') || '[]');
      const latestEvent = eventList.length ? eventList[eventList.length - 1] : 'N/A';

      const now = new Date();
      const reportText = `
📋 Project Heimdall - Event Summary Report
----------------------------------------
🗓 Date: ${now.toLocaleDateString()}  ⏰ Time: ${now.toLocaleTimeString()}
📍 Latest Event: ${latestEvent}
👥 Crowd Level: Medium (Green-Yellow)
🚨 Alerts: No critical alerts
📊 Status: Monitoring
📝 Summary: All systems functioning normally. No security issues detected.

Generated by Event Organizer Dashboard.
`;

      const blob = new Blob([reportText], { type: 'text/plain' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `event-report-${now.getTime()}.txt`;
      link.click();

      showToast("📄 Report generated and downloaded!");
    });
  }
}

// ------------------ CAMERA FEED ------------------
function setupCameraLinks() {
  document.querySelectorAll('a[href^="#"]').forEach(link => {
    link.addEventListener('click', (e) => {
      e.preventDefault();
      const camText = e.target.innerText.toLowerCase();
      const videoId = camText.includes("drone") ?
        camText.replace("drone", "").trim().split(" ")[0] :
        camText.replace("cam", "").trim().split(" ")[0];

      const videoPath = `../assets/videos/${camText.includes("drone") ? `drone${videoId}.mp4` : `cam${videoId}.mp4`}`;

      const videoModal = document.getElementById('videoModal');
      const modalVideo = document.getElementById('modalVideo');

      modalVideo.src = videoPath;
      videoModal.style.display = 'flex';
    });
  });
}

// Close Video Modal
function closeModal() {
  const videoModal = document.getElementById('videoModal');
  const modalVideo = document.getElementById('modalVideo');
  modalVideo.pause();
  modalVideo.src = '';
  videoModal.style.display = 'none';
}

// ------------------ DRONE DASHBOARD ------------------
function checkMissingPersonOnDroneDashboard() {
  const container = document.getElementById('droneScanZone');
  const img = localStorage.getItem('missingPersonImage');
  if (img && container) {
    const face = document.createElement('img');
    face.src = img;
    face.style.maxWidth = '200px';
    face.style.border = '4px solid #00ffd5';
    face.style.borderRadius = '12px';
    face.style.marginBottom = '10px';

    const info = document.createElement('p');
    info.innerText = "🚨 Drone is scanning for this person...";
    info.style.fontWeight = 'bold';

    container.appendChild(face);
    container.appendChild(info);
  }
}

// ------------------ GLOBAL TOAST ------------------
function showToast(message) {
  const toast = document.createElement('div');
  toast.innerText = message;
  toast.style.position = 'fixed';
  toast.style.bottom = '30px';
  toast.style.left = '50%';
  toast.style.transform = 'translateX(-50%)';
  toast.style.background = '#00ffd5';
  toast.style.color = '#000';
  toast.style.padding = '10px 20px';
  toast.style.borderRadius = '10px';
  toast.style.boxShadow = '0 0 15px rgba(0, 255, 213, 0.7)';
  toast.style.zIndex = '9999';
  toast.style.fontWeight = 'bold';
  document.body.appendChild(toast);
  setTimeout(() => {
    toast.remove();
  }, 3000);
}

// ------------------ ON LOAD ------------------
window.addEventListener('DOMContentLoaded', () => {
  loadEvents();
  setupCommunicationPanel();
  setupMissingUpload();
  setupCameraLinks();
  setupReportGenerator();
  checkMissingPersonOnDroneDashboard();
});
